wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.6
    start_time: 1670345755.201911
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.13.5
      8:
      - 2
      - 5
child:
  desc: null
  value: 100
depth:
  desc: null
  value: 3
